version: '3.8'

services:
  back:
    image: gbds234/back:latest
    ports:
      - "8080:8080"
    container_name: back
    restart: always
    depends_on:
    - mysql
    - redis
  front:
    image: gbds234/front:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: front
    restart: always
    depends_on:
    - mysql
    - redis
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dropthevoice
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
    container_name: redis_boot
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
  flask:
    image: gbds234/flask:latest
    restart: always
    container_name: flask
    ports:
      - 5000:5000

volumes:
  esdata1:
    driver: local
  mysql-data:
networks:
  elastic:
    driver: bridge
