server:
  port: 8080

spring:
  profiles:
    active: local
    include: local
  application:
    name: dropthevoice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: smtp.naver.com
    port: 465
    username: tjtkddn97@naver.com
    password: sangwoo97@
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: flase
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  level:
    root: info
